### ISSUE TITLE
libsketchtrial.dylib  Library image not found error

### ISSUE THREAD

**Issue by jaybabani** [gch1p/sketchtrial#4]
Hello,

Getting this error

dyld: could not load inserted library '/Applications/sketchtrial-master/libsketchtrial.dylib' because image not found when executing the sketch.sh file.

SIP is disabled already. Testing with sketch 55.2

**Comment by gch1p** [comment]
Did you run `make`?

**Comment by jaybabani** [comment]
Yes. I double clicked MakeFile and got list of command not found errors. See the screenshot below:

![image](https://user-images.githubusercontent.com/3775102/60384481-e854f100-9a9b-11e9-8a4a-23f299584b3c.png)

**Comment by gch1p** [comment]
I'm not sure what you're doing. It looks like you're trying to run Makefile as a shell script?

You need to do `cd /Applications/sketchtrial-master`, then run `make`.

**Comment by jaybabani** [comment]
Ah. Thank you so much.. It worked.

I am quite new to Mac OS. Yes. you are right.. I was running makefile in shell script, so the error.

It works alright.. thank you once again.

Will be waiting for SIP enabled version of your script in future. :)
