### ISSUE TITLE
Sketch encounters a problem and does not open

### ISSUE THREAD

**Issue by daanvr** [gch1p/sketchtrial#5]
hi, I followed all the steps as carefully as possible, however, when I open sketch using "sketch.sh" it crashes. I get the following "problem report"

`Process:               Sketch [953]
Path:                  /Applications/Sketch.app/Contents/MacOS/Sketch
Identifier:            Sketch
Version:               55.2 (78181)
Code Type:             X86-64 (Native)
Parent Process:        ??? [949]
Responsible:           Sketch [953]
User ID:               501

Date/Time:             2019-07-13 11:03:10.204 +0200
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12
Anonymous UUID:        977BF22F-AE3E-13C2-226B-1E6173B67D04

Time Awake Since Boot: 830 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x9] <unknown>

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_INSERT_LIBRARIES=/Users/daan/Downloads/sketchtrial-master/libsketchtrial.dylib

Dyld Error Message:
  could not load inserted library '/Users/daan/Downloads/sketchtrial-master/libsketchtrial.dylib' because image not found

Binary Images:
       0x10c026000 -        0x10c38bf0f +com.bohemiancoding.sketch3 (55.2 - 78181) <B3DE0512-DCDB-3713-8CCB-B8ED189C2C3B> /Applications/Sketch.app/Contents/MacOS/Sketch
       0x115c1f000 -        0x115c896ef  dyld (655.1.1) <F217F7F8-A795-3109-B77F-B1E2277F3E3B> /usr/lib/dyld

Model: MacBookAir5,1, BootROM 255.0.0.0.0, 2 processors, Intel Core i5, 1,7 GHz, 8 GB, SMC 2.4f19
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D5434353153364D465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE9), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1325.2)
Bluetooth: Version 6.0.11f4, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM256E, 251 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Air, Apple Inc., 23.4
`

Any suggestion on what goes wrong?

**Comment by gch1p** [comment]
Have you built the library?

**Comment by daanvr** [comment]
Which of the staps is that?
I did the following:
1: download the GitHub folder
2: I opened terminal
3: I copies and past the 3 lines form the readme into the terminal: "git clone [...] make"
4: pressed enter
5: the terminal did some processes
6: I copied the path to "sketch.sh" into the terminal and press enter again
7: got the error

**Comment by gch1p** [comment]
The `git clone ...` line clones this repository to your machine, you don't need to download anything. It seems you have built the library in one directory and trying to launch `sketch.sh` from another.

**Comment by gch1p** [comment]
Either run `make` in directory of unpacked archive you downloaded and use that, or delete it and use the cloned repo.

**Comment by daanvr** [comment]
Solved! You are right I was using two different folders with a clone.
Thank you for helping me! 
![Screenshot 2019-07-17 at 09 56 48](https://user-images.githubusercontent.com/4609765/61357937-8a851f00-a879-11e9-8803-9bb887d7accb.png)
