### ISSUE TITLE
Doesn't work in version 57.1

### ISSUE THREAD

**Issue by Swiftnesses** [gch1p/sketchtrial#8]
It appears this no longer extends the trial.

**Comment by leetoufong** [comment]
I can vouch for this. No longer working as of 8/26 with version `57.1`.

**Comment by lpaicheur** [comment]
Every versions after the `v55.2` does not work.

**Comment by gch1p** [comment]
Works for me. Have you disabled SIP?

<img width="916" alt="Screenshot 2019-10-06 at 15 06 35" src="https://user-images.githubusercontent.com/18737999/64430224-1700d080-d0b8-11e9-8e3c-486ebc81573d.png">

**Comment by thebrodmann** [comment]
What is SIP?

**Comment by Oliver-Hull-III** [comment]
System Integrity Protection

**Comment by gch1p** [comment]
System Integrity Protection. See the last paragraph of the README.

**Comment by the-dr-lazy** [comment]
Ah, I saw it and deleted my comment. BTW on 55.2, it worked without disabling SIP and now I disable the SIP then on 57.1 it worked.

**Comment by gch1p** [comment]
OK, closing for now.
